### ISSUE TITLE
Review GraphQL 2020 Spec Changes

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#1199]
We have already implemented quite a lot of the GraphQL 2021 spec. We still need to review the changes again and tick of what is done and mark what we still have to do. We should add a checklist into this issue that links to all the spec change prs.

The release of V11 and the GraphQL Spec 2020 align quite well.

- [ ] https://github.com/graphql/graphql-spec/pull/601 (in progress)
- [ ] https://github.com/graphql/graphql-spec/pull/599 (in progress)
- [x] https://github.com/graphql/graphql-spec/pull/472
- [x] https://github.com/graphql/graphql-spec/pull/466
- [ ] https://github.com/graphql/graphql-spec/pull/445 (accepted for 2020)
- [x] https://github.com/graphql/graphql-spec/pull/373
- [ ] graphql/graphql-spec#510: 8b4f7e5
- [x] graphql/graphql-spec#472
- [x] graphql/graphql-spec#470
- [x] graphql/graphql-spec#649
- [ ] https://github.com/ChilliCream/hotchocolate/issues/1463

**Comment by michaelstaib** [comment]
@PascalSenn do you fancy some spec work? We need to review / re-read the spec. There are still not all items merged so we should first look into the open drafts.

If you are not interested then I will do it. If you are interested then we should organize this work here and divide up the review and implementation.

**Comment by michaelstaib** [comment]
This is not pressing... we are pretty far already on the spec... I just want to get it in a more organized form.

**Comment by PascalSenn** [comment]
This one? https://graphql.github.io/graphql-spec/draft/?

**Comment by michaelstaib** [comment]
Yeah but there are not all the things in.

https://github.com/graphql/graphql-spec/pulls?q=is%3Aopen+is%3Apr+label%3A%22📄+Draft+%28RFC+2%29%22
https://github.com/graphql/graphql-spec/pulls?q=is%3Apr+label%3A%22🏁+Accepted+%28RFC+3%29%22+is%3Aclosed

**Comment by tobias-tengler** [comment]
Closing, since I think this is done.
