### ISSUE TITLE
Introducing HotChocolate.Types.Scalars

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/hotchocolate#2927]
By using scalar types for leaf fields, you can build expressive and easy to understand schemas.

the Guild implemented a very useful set of scalars in JavaScript. We want to port these scalars to HotChocolate and make them available for you.
We already unsealed all scalar types and created a test base that helps us test new scalars.

We have a many people in the community that would like to contribute to HotChocolate but do not know where to start. This issue is an incredibly good starter issue.

# The Scalars

1. [x] [scalar Time](https://github.com/Urigo/graphql-scalars#time)
1. [x] scalar DateTime
1. [x] [scalar Duration](https://github.com/Urigo/graphql-scalars#duration)
1. [x] [scalar UtcOffset](https://github.com/Urigo/graphql-scalars#utcoffset)
1.  [x] [scalar LocalDate](https://github.com/Urigo/graphql-scalars#localdate)
1.  [x] [scalar LocalTime](https://github.com/Urigo/graphql-scalars#localtime)
1.  [x] [scalar LocalEndTime](https://github.com/Urigo/graphql-scalars#localendtime)
1.  [x] [scalar EmailAddress](https://github.com/Urigo/graphql-scalars#emailaddress)
1.  [x] [scalar NegativeFloat](https://github.com/Urigo/graphql-scalars#negativefloat)
1.  [x] [~~scalar NegativeInt~~](https://github.com/Urigo/graphql-scalars#negativeint) Issues #2939 PR #2940
1.  [x]  [~~scalar NonEmptyString~~](https://github.com/Urigo/graphql-scalars#nonemptystring)
1.  [x] [~~scalar NonNegativeFloat~~](https://github.com/Urigo/graphql-scalars#nonnegativefloat)Issues #3013 PR #3015
1.  [x] [scalar NonNegativeInt](https://github.com/Urigo/graphql-scalars#nonnegativeint)
1.  [x] [scalar NonPositiveFloat](https://github.com/Urigo/graphql-scalars#nonpositivefloat)
1. [x]  [scalar NonPositiveInt](https://github.com/Urigo/graphql-scalars#nonpositiveint)
1.  [x] [scalar PhoneNumber](https://github.com/Urigo/graphql-scalars#phonenumber)
1.  [x] [~~scalar PositiveFloat~~](https://github.com/Urigo/graphql-scalars#positivefloat) Issues #2928 PR #2929
1. [x] [~~scalar PositiveInt~~](https://github.com/Urigo/graphql-scalars#positiveint)
1. [x]  [scalar PostalCode](https://github.com/Urigo/graphql-scalars#postalcode)
1.  [x] [~~scalar UnsignedFloat~~](https://github.com/Urigo/graphql-scalars#unsignedfloat) Will not be included
1. [x]  [scalar UnsignedInt](https://github.com/Urigo/graphql-scalars#unsignedint)
1.  [x]  [~~scalar URL~~](https://github.com/Urigo/graphql-scalars#url)
1.  [x] [~~scalar ObjectID~~](https://github.com/Urigo/graphql-scalars#objectid) Belongs into the mongodb package
1.  [x] [scalar BigInt](https://github.com/Urigo/graphql-scalars#bigint) in the works
1.  [x] [~~scalar Long~~](https://github.com/Urigo/graphql-scalars#long)
1.  [x] [scalar SafeInt](https://github.com/Urigo/graphql-scalars#safeint)
1.  [x]  [~~scalar UUID~~](https://github.com/Urigo/graphql-scalars#uuid)
1.  [x] [scalar GUID](https://github.com/Urigo/graphql-scalars#guid)
1.  [x] [scalar HexColorCode](https://github.com/Urigo/graphql-scalars#hexcolorcode)
1.  [x] [scalar HSL](https://github.com/Urigo/graphql-scalars#hsl)
1. [x]  [scalar HSLA](https://github.com/Urigo/graphql-scalars#hsla)
1.  [x] [scalar IPv4](https://github.com/Urigo/graphql-scalars#ipv4)
1.  [x] [scalar IPv6](https://github.com/Urigo/graphql-scalars#ipv6)
1.  [x] [scalar ISBN](https://github.com/Urigo/graphql-scalars#isbn)
1.  [x] [scalar MAC](https://github.com/Urigo/graphql-scalars#mac)
1.  [x] [scalar Port](https://github.com/Urigo/graphql-scalars#port) 
1.  [x]  [scalar RGB](https://github.com/Urigo/graphql-scalars#rgb) 
1.  [x] [scalar RGBA](https://github.com/Urigo/graphql-scalars#rgba)  
1.  [ ] [~~scalar USCurrency~~](https://github.com/Urigo/graphql-scalars#uscurrency) deprecated for`LocalCurrency`
1.  [ ] [scalar Currency](https://github.com/Urigo/graphql-scalars#currency)  
1.  [x] [scalar LocalCurrency]() in works @wonbyte 
1.  [x] [scalar JSON](https://github.com/Urigo/graphql-scalars#json)
1.  [x] [scalar JSONObject](https://github.com/Urigo/graphql-scalars#jsonobject)
1.  [x] [scalar Byte](https://github.com/Urigo/graphql-scalars#byte) 
1.  [x] [scalar Void](https://github.com/Urigo/graphql-scalars#void)

# How to Contribute
If you would like to help, this is whats need to be done:
1. Choose a scalar you would like to implement from the list above and [create an issue for it](https://github.com/ChilliCream/hotchocolate/issues/new?assignees=&labels=&template=feature_request.md).
   Use this issue as a template for title and body: #2928
2. Create a branch based on  [feat/scalar-types](https://github.com/ChilliCream/hotchocolate/tree/feat/scalar-types).
   Our branch policy is [three letter shortcut of your name]/[what your branch does].
   In my case (Pascal Senn) this would be `pse` and i will implement the `PositiveInt` scalar

   `pse/add-positive-in-scalar`
```
git clone https://github.com/ChilliCream/hotchocolate.git
git checkout -b pse/add-positive-int-scalar
```
> You will need contribution rights to push your changes to the repository once you finished your work. Reach out to Michael on slack or add a comment on this issue that you need contribution rights on the repository, we will provide you with the correct permissions.
>
> Alternatively you can also fork the project and make the changes in your fork. You can then create a pull request from your fork onto ChilliCream/HotChocolate. This way you do not need to wait for the permissions.
3.  You have to implement the scalar, add tests and add documentation. In what order you do this is up to you. You can take this pull request as a reference for what has to be implemented: #2929

You must take five methods in consideration
```csharp
        /// This method defines if the given runtimeValue is possibly of this type
        ///
        /// This method is executed in various places. E.g. the validation uses this
        /// method to validate if a value is correct
        protected override bool IsInstanceOfType(string runtimeValue)
        {
            ...
        }

        /// This method defines if the given value syntax is possibly of this type
        ///
        /// This method is executed in various places. E.g. the validation uses this
        /// method to validate if a input value is correct
        protected override bool IsInstanceOfType(StringValueNode valueSyntax)
        {
            ...
        }

        /// Parses a runtime value of this type into a GraphQL value syntax representation.
        ///
        /// <exception cref="SerializationException">
        /// Unable to parse the given <paramref name="resultValue"/>
        /// into a GraphQL value syntax representation of this type.
        /// </exception>
        protected override string ParseLiteral(StringValueNode valueSyntax)
        {
            ...
        }

        /// Parses a result value of this into a GraphQL value syntax representation.
        ///
        /// <exception cref="SerializationException">
        /// Unable to parse the given <paramref name="resultValue"/>
        /// into a GraphQL value syntax representation of this type.
        /// </exception>
        protected override StringValueNode ParseValue(string runtimeValue)
        {
            ...
        } 

        /// Serializes a runtime value into a result value (this method is used e.g. for variables)
        /// Returns false if serialization failed
        public override bool TrySerialize(object? runtimeValue, out object? resultValue)
        { 
        }

        /// Deserializes a runtime value into a result value (this method is used e.g. for variables)
        /// Returns false if deserialization failed
        public override bool TryDeserialize(object? resultValue, out object? runtimeValue)
        { 
        }
```
4. Create a pull request targeting the branch `feat/scalar-types`.  
5. Wait for a review, resolve the comments, wait for a merge, celebrate 🎉

**Comment by DorianGreen** [comment]
In my project, I have the requirement to work with Local DateTime, UTC DateTime, and DateTimeOffset.
The current version of the DateTime scalar supports both DateTimeOffset and UTC Date Time.

I am intending to define a LocalDateTime scalar in my project and can contribute it when its done.

I think it could also be useful to have a DateTimeObject type, that will allow consumers to pick what parts of a date they are interested in without needing to explicitly define the values in the schema.

For TimeZones I intend to define a TimeZoneId scalar based on IANA values, and a TimeZoneObject type with some values for display names, abbreviations, DST flag, etc..

**Comment by mvestergaard** [comment]
@DorianGreen We just had the same challenge in our project and ended up using [NodaTime's LocalDateTime](https://nodatime.org/3.0.x/api/NodaTime.LocalDateTime.html) and a custom scalar type to map to and from that.
