### ISSUE TITLE
Spec: Allow interfaces to implement other interfaces

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#703]
**Spec PR:**
https://github.com/graphql/graphql-spec/pull/373

**Reference Implementation:**
https://github.com/graphql/graphql-js/pull/2084

**Tasks:**

- [x] Add Parser Changes
- [x] Add Type System Changes
- [x] Add Validation Changes
- [x] Add Runtime Changes
- [x] Update Introspection Tools

**Comment by michaelstaib** [comment]
https://github.com/graphql/graphql-js/pull/2084

**Comment by lindeberg** [comment]
Should this be working now? I'm having issues.

**Comment by PascalSenn** [comment]
@lindeberg  yes this should work. can you open a new issue? It's likely that we overlook comments on closed issues :)
